version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user_analytics_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-initdb/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.7.1-python3.10
    container_name: user_analytics_airflow_init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_metadata
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: >
      bash -c "airflow db init &&
      airflow users create
      --username admin
      --firstname Admin
      --lastname Admin
      --role Admin
      --email admin@example.com
      --password admin"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:2.7.1-python3.10
    container_name: user_analytics_airflow_webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_metadata
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas pyarrow sqlalchemy psycopg2-binary requests pytest"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.10
    container_name: user_analytics_airflow_scheduler
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_metadata
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas pyarrow sqlalchemy psycopg2-binary requests pytest"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always

volumes:
  postgres_data:
